CREATE TABLE IF NOT EXISTS burial (
    APPLICANTID INT AUTO_INCREMENT PRIMARY KEY,
    APPLICANTNAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    FAMILYINCOME VARCHAR(255) NOT NULL,
    EMAILADDRESS VARCHAR(255) NOT NULL,
    PHONENUMBER VARCHAR(255) NOT NULL,
    DECEASEDNAME VARCHAR(255) NOT NULL,
    CAUSEOFDEATH VARCHAR(255) NOT NULL
);